### ISSUE TITLE
Updating environment on each new release

### ISSUE THREAD

**Issue by edublancas** [ploomber/binder-env#3]
We use this repository to store all the dependencies our packages need to be tested on binder. This means that the environment installs sklearn-evaluation, ploomber (and all examples in ploomber/projects), soorgeon, jupysql, etc.

the environment is cached in a Docker image, and it's updated only when we create a new commit here and re-open binder.ploomber.io (to trigger the new Docker build). so whenever we make a new package release, we must re-build the docker image to ensure the latest version is used; otherwise, the examples will break if we introduce new features or break API changes.

I think the simplest way is to schedule a github action here that generates a new empty commit and calls to binder.ploomber.io; this way we'll force the Docker building process.

thoughts? @idomic

**Comment by idomic** [comment]
Why don't we just an extra step from the release pipeline?
I think if we do empty commits + gh action it might make the docker caching redundant no?

**Comment by edublancas** [comment]
> Why don't we just an extra step from the release pipeline?

because releasing to PyPI is a manual process atm. I run one command on my laptop that uploads the release.

> I think if we do empty commits + gh action it might make the docker caching redundant no?

why redundant? the purpose is to force a re-build. after it, users can open binder and it'll use the cached docker image

**Comment by idomic** [comment]
Sure we can try this approach and see how it goes.

**Comment by edublancas** [comment]
fixed. I configured an action that runs every 24 hours, updates the environment and calls binder to re-build the docker image. tested on https://github.com/ploomber/binder-env/commit/f754547a77329b67a52860d5a046426db66ca45c
